---
title: "Case Study: Electric Power Consumption"
author: "Lauri Varmann"
date: "18 December 2019"
output:
  html_document:
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(data.table)
library(countrycode)
library(ggplot2)
library(magrittr)
library(ggrepel)
library(knitr)
library(kableExtra)
```

# Data Processing

```{r readData, warning=FALSE}
ep <- fread(here("data", "epdata.csv"), 
            skip = 4, header = TRUE,
            check.names = TRUE)

# Add Continent to EPC dataset.
cl <- as.data.table(codelist)[, .(continent, wb)]

epcl <- merge(ep, cl, by.x = "Country.Code", by.y = "wb", all.x = TRUE)
setnames(epcl, c("continent"), c("Continent"))

EPC <- melt(epcl,
           id.vars = c("Continent", "Country.Name", "Country.Code", "Indicator.Code"),
           measure = patterns("^X"),
           variable.name = "YearC",
           value.name = c("pctWiP"),
           na.rm = TRUE)
```
